workflows:

    android-release:

        name: Android Release Workflow

        max_build_duration: 120

        instance_type: mac_mini_m2

        environment:
            android_signing:
                - mimi-receipt-key
            vars:
                PACKAGE_NAME: "com.example.reciept_tracker"

        scripts:
            - name: Get Flutter dependencies
              script: |
                flutter pub get

            - name: Build Android App Bundle
              script: |
                # Build with release signing configured in build.gradle.kts
                # Gradle will use CM_* environment variables for signing
                flutter build appbundle --release

        artifacts:
            - build/app/outputs/**/*.aab
            - build/app/outputs/**/*.apk

        publishing:
            email:
                recipients:
                    - asumahbanda3@gmail.com
                notify:
                    success: true
                    failure: false